//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace Vcredit.WeiXin.RestService.CheckCardService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CheckCardServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CheckCardService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBankCardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CheckCardService() {
            this.Url = global::Vcredit.WeiXin.RestService.Properties.Settings.Default.Vcredit_WeiXin_RestService_CheckCardService_CheckCardService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event CheckBankCardCompletedEventHandler CheckBankCardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckBankCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseResult CheckBankCard(CheckCardInfo cardInfo) {
            object[] results = this.Invoke("CheckBankCard", new object[] {
                        cardInfo});
            return ((ResponseResult)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBankCardAsync(CheckCardInfo cardInfo) {
            this.CheckBankCardAsync(cardInfo, null);
        }
        
        /// <remarks/>
        public void CheckBankCardAsync(CheckCardInfo cardInfo, object userState) {
            if ((this.CheckBankCardOperationCompleted == null)) {
                this.CheckBankCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBankCardOperationCompleted);
            }
            this.InvokeAsync("CheckBankCard", new object[] {
                        cardInfo}, this.CheckBankCardOperationCompleted, userState);
        }
        
        private void OnCheckBankCardOperationCompleted(object arg) {
            if ((this.CheckBankCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBankCardCompleted(this, new CheckBankCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckCardInfo {
        
        private long checkCardIDField;
        
        private string checkCardCodeField;
        
        private string platformField;
        
        private string toAccountField;
        
        private string accountNoField;
        
        private string accountNameField;
        
        private string proviceField;
        
        private string cityField;
        
        private string bankBranchField;
        
        private string accountBankField;
        
        private string identityCardField;
        
        private string resultField;
        
        private string resultDescField;
        
        private string telField;
        
        private System.DateTime sendTimeField;
        
        private System.Nullable<System.DateTime> finishTimeField;
        
        private byte stateField;
        
        private System.DateTime createTimeField;
        
        private DeductRecord[] checkCardRecordsField;
        
        /// <remarks/>
        public long CheckCardID {
            get {
                return this.checkCardIDField;
            }
            set {
                this.checkCardIDField = value;
            }
        }
        
        /// <remarks/>
        public string CheckCardCode {
            get {
                return this.checkCardCodeField;
            }
            set {
                this.checkCardCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string ToAccount {
            get {
                return this.toAccountField;
            }
            set {
                this.toAccountField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
            }
        }
        
        /// <remarks/>
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public string Provice {
            get {
                return this.proviceField;
            }
            set {
                this.proviceField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string BankBranch {
            get {
                return this.bankBranchField;
            }
            set {
                this.bankBranchField = value;
            }
        }
        
        /// <remarks/>
        public string AccountBank {
            get {
                return this.accountBankField;
            }
            set {
                this.accountBankField = value;
            }
        }
        
        /// <remarks/>
        public string IdentityCard {
            get {
                return this.identityCardField;
            }
            set {
                this.identityCardField = value;
            }
        }
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public string Tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FinishTime {
            get {
                return this.finishTimeField;
            }
            set {
                this.finishTimeField = value;
            }
        }
        
        /// <remarks/>
        public byte State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public DeductRecord[] CheckCardRecords {
            get {
                return this.checkCardRecordsField;
            }
            set {
                this.checkCardRecordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeductRecord {
        
        private long deductRecordIDField;
        
        private long deductInstructionIDField;
        
        private int deductBatchIDField;
        
        private string deductPlatformField;
        
        private string interfaceKindField;
        
        private string merchantNoField;
        
        private string contentField;
        
        private string resultCodeField;
        
        private string resultDescField;
        
        private System.DateTime createTimeField;
        
        private DeductInstruction deductInstructionField;
        
        private DeductBatch deductBatchField;
        
        private bool isResponseField;
        
        /// <remarks/>
        public long DeductRecordID {
            get {
                return this.deductRecordIDField;
            }
            set {
                this.deductRecordIDField = value;
            }
        }
        
        /// <remarks/>
        public long DeductInstructionID {
            get {
                return this.deductInstructionIDField;
            }
            set {
                this.deductInstructionIDField = value;
            }
        }
        
        /// <remarks/>
        public int DeductBatchID {
            get {
                return this.deductBatchIDField;
            }
            set {
                this.deductBatchIDField = value;
            }
        }
        
        /// <remarks/>
        public string DeductPlatform {
            get {
                return this.deductPlatformField;
            }
            set {
                this.deductPlatformField = value;
            }
        }
        
        /// <remarks/>
        public string InterfaceKind {
            get {
                return this.interfaceKindField;
            }
            set {
                this.interfaceKindField = value;
            }
        }
        
        /// <remarks/>
        public string MerchantNo {
            get {
                return this.merchantNoField;
            }
            set {
                this.merchantNoField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public DeductInstruction DeductInstruction {
            get {
                return this.deductInstructionField;
            }
            set {
                this.deductInstructionField = value;
            }
        }
        
        /// <remarks/>
        public DeductBatch DeductBatch {
            get {
                return this.deductBatchField;
            }
            set {
                this.deductBatchField = value;
            }
        }
        
        /// <remarks/>
        public bool IsResponse {
            get {
                return this.isResponseField;
            }
            set {
                this.isResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeductInstruction {
        
        private long deductInstructionIDField;
        
        private string deductInstructionCodeField;
        
        private int deductTaskIDField;
        
        private int deductBatchIDField;
        
        private string deductPlatformField;
        
        private string accountBankField;
        
        private string accountNoField;
        
        private string accountNameField;
        
        private decimal amountField;
        
        private string toAccountField;
        
        private string identityCardField;
        
        private string resultField;
        
        private string resultDescField;
        
        private string lendingSideKeyField;
        
        private string remarkField;
        
        private System.DateTime createTimeField;
        
        private DeductBatch deductBatchField;
        
        private DeductTask deductTaskField;
        
        private DeductRecord[] deductRecordsField;
        
        /// <remarks/>
        public long DeductInstructionID {
            get {
                return this.deductInstructionIDField;
            }
            set {
                this.deductInstructionIDField = value;
            }
        }
        
        /// <remarks/>
        public string DeductInstructionCode {
            get {
                return this.deductInstructionCodeField;
            }
            set {
                this.deductInstructionCodeField = value;
            }
        }
        
        /// <remarks/>
        public int DeductTaskID {
            get {
                return this.deductTaskIDField;
            }
            set {
                this.deductTaskIDField = value;
            }
        }
        
        /// <remarks/>
        public int DeductBatchID {
            get {
                return this.deductBatchIDField;
            }
            set {
                this.deductBatchIDField = value;
            }
        }
        
        /// <remarks/>
        public string DeductPlatform {
            get {
                return this.deductPlatformField;
            }
            set {
                this.deductPlatformField = value;
            }
        }
        
        /// <remarks/>
        public string AccountBank {
            get {
                return this.accountBankField;
            }
            set {
                this.accountBankField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
            }
        }
        
        /// <remarks/>
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string ToAccount {
            get {
                return this.toAccountField;
            }
            set {
                this.toAccountField = value;
            }
        }
        
        /// <remarks/>
        public string IdentityCard {
            get {
                return this.identityCardField;
            }
            set {
                this.identityCardField = value;
            }
        }
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public string LendingSideKey {
            get {
                return this.lendingSideKeyField;
            }
            set {
                this.lendingSideKeyField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public DeductBatch DeductBatch {
            get {
                return this.deductBatchField;
            }
            set {
                this.deductBatchField = value;
            }
        }
        
        /// <remarks/>
        public DeductTask DeductTask {
            get {
                return this.deductTaskField;
            }
            set {
                this.deductTaskField = value;
            }
        }
        
        /// <remarks/>
        public DeductRecord[] DeductRecords {
            get {
                return this.deductRecordsField;
            }
            set {
                this.deductRecordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeductBatch {
        
        private int deductBatchIDField;
        
        private string deductBatchCodeField;
        
        private string deductPlatformField;
        
        private string interfaceKindField;
        
        private int cntField;
        
        private int backCntField;
        
        private decimal requestedAmtField;
        
        private decimal receivedAmtField;
        
        private string deductContentField;
        
        private int deductTaskIDField;
        
        private string toAccountField;
        
        private System.DateTime sendTimeField;
        
        private System.Nullable<System.DateTime> finishTimeField;
        
        private byte stateField;
        
        private System.DateTime createTimeField;
        
        private DeductInstruction[] deductInstructionsField;
        
        private DeductRecord[] deductRecordsField;
        
        /// <remarks/>
        public int DeductBatchID {
            get {
                return this.deductBatchIDField;
            }
            set {
                this.deductBatchIDField = value;
            }
        }
        
        /// <remarks/>
        public string DeductBatchCode {
            get {
                return this.deductBatchCodeField;
            }
            set {
                this.deductBatchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DeductPlatform {
            get {
                return this.deductPlatformField;
            }
            set {
                this.deductPlatformField = value;
            }
        }
        
        /// <remarks/>
        public string InterfaceKind {
            get {
                return this.interfaceKindField;
            }
            set {
                this.interfaceKindField = value;
            }
        }
        
        /// <remarks/>
        public int Cnt {
            get {
                return this.cntField;
            }
            set {
                this.cntField = value;
            }
        }
        
        /// <remarks/>
        public int BackCnt {
            get {
                return this.backCntField;
            }
            set {
                this.backCntField = value;
            }
        }
        
        /// <remarks/>
        public decimal RequestedAmt {
            get {
                return this.requestedAmtField;
            }
            set {
                this.requestedAmtField = value;
            }
        }
        
        /// <remarks/>
        public decimal ReceivedAmt {
            get {
                return this.receivedAmtField;
            }
            set {
                this.receivedAmtField = value;
            }
        }
        
        /// <remarks/>
        public string DeductContent {
            get {
                return this.deductContentField;
            }
            set {
                this.deductContentField = value;
            }
        }
        
        /// <remarks/>
        public int DeductTaskID {
            get {
                return this.deductTaskIDField;
            }
            set {
                this.deductTaskIDField = value;
            }
        }
        
        /// <remarks/>
        public string ToAccount {
            get {
                return this.toAccountField;
            }
            set {
                this.toAccountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FinishTime {
            get {
                return this.finishTimeField;
            }
            set {
                this.finishTimeField = value;
            }
        }
        
        /// <remarks/>
        public byte State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public DeductInstruction[] DeductInstructions {
            get {
                return this.deductInstructionsField;
            }
            set {
                this.deductInstructionsField = value;
            }
        }
        
        /// <remarks/>
        public DeductRecord[] DeductRecords {
            get {
                return this.deductRecordsField;
            }
            set {
                this.deductRecordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseResult {
        
        private bool resultField;
        
        private string resultDescField;
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeductTask {
        
        private int deductTaskIDField;
        
        private int cntField;
        
        private decimal requestedAmtField;
        
        private decimal receivedAmtField;
        
        private byte stateField;
        
        private int operatorIDField;
        
        private System.DateTime createTimeField;
        
        private DeductInstruction[] deductInstructionsField;
        
        /// <remarks/>
        public int DeductTaskID {
            get {
                return this.deductTaskIDField;
            }
            set {
                this.deductTaskIDField = value;
            }
        }
        
        /// <remarks/>
        public int Cnt {
            get {
                return this.cntField;
            }
            set {
                this.cntField = value;
            }
        }
        
        /// <remarks/>
        public decimal RequestedAmt {
            get {
                return this.requestedAmtField;
            }
            set {
                this.requestedAmtField = value;
            }
        }
        
        /// <remarks/>
        public decimal ReceivedAmt {
            get {
                return this.receivedAmtField;
            }
            set {
                this.receivedAmtField = value;
            }
        }
        
        /// <remarks/>
        public byte State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public DeductInstruction[] DeductInstructions {
            get {
                return this.deductInstructionsField;
            }
            set {
                this.deductInstructionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CheckBankCardCompletedEventHandler(object sender, CheckBankCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBankCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBankCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591