//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcredit.WeiXin.RestService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.100.12.68:8080/GateWay/VcreditNPGateway.asmx")]
        public string Vcredit_WeiXin_RestService_VcreditNPGateway_VcreditNPGateway {
            get {
                return ((string)(this["Vcredit_WeiXin_RestService_VcreditNPGateway_VcreditNPGateway"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.100.12.18:9999/OCRService.asmx")]
        public string Vcredit_WeiXin_RestService_OCRService_OCRService {
            get {
                return ((string)(this["Vcredit_WeiXin_RestService_OCRService_OCRService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.138.60.18:6868/AuthenticationService.asmx")]
        public string Vcredit_WeiXin_RestService_AuthenticationService_AuthenticationService {
            get {
                return ((string)(this["Vcredit_WeiXin_RestService_AuthenticationService_AuthenticationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.138.60.18:5555/CheckCardService.asmx")]
        public string Vcredit_WeiXin_RestService_CheckCardService_CheckCardService {
            get {
                return ((string)(this["Vcredit_WeiXin_RestService_CheckCardService_CheckCardService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.6.155:8812/GateWay/RCService.asmx")]
        public string Vcredit_WeiXin_RestService_RCWebService_RCWebService {
            get {
                return ((string)(this["Vcredit_WeiXin_RestService_RCWebService_RCWebService"]));
            }
        }
    }
}
