//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vcredit.NetSpider.RestService.VBSSpiderServiceCallback {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VBSSpiderServiceCallback.SpiderServiceCallbackSoap")]
    public interface SpiderServiceCallbackSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ECommerceInfoJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecutorSpiderTaobaoSellerCallback", ReplyAction="*")]
        Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackResponse ExecutorSpiderTaobaoSellerCallback(Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecutorSpiderTaobaoSellerCallbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecutorSpiderTaobaoSellerCallback", Namespace="http://tempuri.org/", Order=0)]
        public Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackRequestBody Body;
        
        public ExecutorSpiderTaobaoSellerCallbackRequest() {
        }
        
        public ExecutorSpiderTaobaoSellerCallbackRequest(Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecutorSpiderTaobaoSellerCallbackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Bid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ECommerceInfoJson;
        
        public ExecutorSpiderTaobaoSellerCallbackRequestBody() {
        }
        
        public ExecutorSpiderTaobaoSellerCallbackRequestBody(int Bid, string ECommerceInfoJson) {
            this.Bid = Bid;
            this.ECommerceInfoJson = ECommerceInfoJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecutorSpiderTaobaoSellerCallbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecutorSpiderTaobaoSellerCallbackResponse", Namespace="http://tempuri.org/", Order=0)]
        public Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackResponseBody Body;
        
        public ExecutorSpiderTaobaoSellerCallbackResponse() {
        }
        
        public ExecutorSpiderTaobaoSellerCallbackResponse(Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecutorSpiderTaobaoSellerCallbackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ExecutorSpiderTaobaoSellerCallbackResult;
        
        public ExecutorSpiderTaobaoSellerCallbackResponseBody() {
        }
        
        public ExecutorSpiderTaobaoSellerCallbackResponseBody(bool ExecutorSpiderTaobaoSellerCallbackResult) {
            this.ExecutorSpiderTaobaoSellerCallbackResult = ExecutorSpiderTaobaoSellerCallbackResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SpiderServiceCallbackSoapChannel : Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.SpiderServiceCallbackSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpiderServiceCallbackSoapClient : System.ServiceModel.ClientBase<Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.SpiderServiceCallbackSoap>, Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.SpiderServiceCallbackSoap {
        
        public SpiderServiceCallbackSoapClient() {
        }
        
        public SpiderServiceCallbackSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpiderServiceCallbackSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpiderServiceCallbackSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpiderServiceCallbackSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackResponse Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.SpiderServiceCallbackSoap.ExecutorSpiderTaobaoSellerCallback(Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackRequest request) {
            return base.Channel.ExecutorSpiderTaobaoSellerCallback(request);
        }
        
        public bool ExecutorSpiderTaobaoSellerCallback(int Bid, string ECommerceInfoJson) {
            Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackRequest inValue = new Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackRequest();
            inValue.Body = new Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackRequestBody();
            inValue.Body.Bid = Bid;
            inValue.Body.ECommerceInfoJson = ECommerceInfoJson;
            Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.ExecutorSpiderTaobaoSellerCallbackResponse retVal = ((Vcredit.NetSpider.RestService.VBSSpiderServiceCallback.SpiderServiceCallbackSoap)(this)).ExecutorSpiderTaobaoSellerCallback(inValue);
            return retVal.Body.ExecutorSpiderTaobaoSellerCallbackResult;
        }
    }
}
