SELECT  BusinessID ,
        DSeqType ,
        PeriodType ,
        CustomerID ,
        SalesManID ,
        ProductType ,
        LoanCapital ,
        ResidualCapital ,
        LoanPeriod ,
        LoanTime ,
        InterestRate ,
        ServiceRate ,
        PenaltyRate ,
        AdvanceFee ,
        EarnestAmt ,
        Premium ,
        SecondSales ,
        BusinessStatus ,
        CLoanStatus ,
        LawsuitStatus ,
        ContractNo ,
        BankKey ,
        SavingCard ,
        LendingSideKey ,
        LendingSideID ,
        ServiceSideKey ,
        ServiceSideID ,
        GuaranteeSideKey ,
        GuaranteeSideID ,
        ConstructionBankNo ,
        ReceiptVersion ,
        OverMonth ,
        OverAmount ,
        CurrentOverAmount ,
        BranchKey ,
        LoanKind ,
        CreateTime ,
        SavingUser ,
        PaymentDate ,
        OtherAmount ,
        ToGuaranteeTime ,
        ToLitigationTime ,
        ClearLoanTime ,
        IsRepayment ,
        LawsuitCode ,
        ProceduresAmout ,
        IsFullInvoice ,
        GuaranteeNum ,
        FrozenNo ,
        ConstructSedNo ,
        SalesTeam ,
        DepositRate ,
        SignTime ,
        DucImgPath ,
        FromSource ,
        RelativeDate ,
        ProceduresRate ,
        SubBranch ,
        ProductKind ,
        PrincipalPunish ,
        ServicePunish ,
        SubmitTime ,
        NextBillDate ,
        SaleMode ,
        ToGuaranteeAmt ,
        Operable ,
        Region ,
        ClearLoanType ,
        ClearLoanRemark ,
        SpecailPolicy ,
        CapitalRate ,
        FundSource ,
        ManagementRate ,
        ChannelRate ,
        CollectionRate,
        YearRate
FROM dbo.Business WITH(NOLOCK) 
WHERE BusinessID={0}

SELECT  BillID ,
        BusinessID ,
        CustomerID ,
        BillType ,
        BillStatus ,
        BillMonth ,
        CompanyKey ,
        BeginTime ,
        EndTime ,
        LimitTime ,
        CreateTime ,
        OperatorID ,
        IsCurrent ,
        FullPaidTime ,
        IsShelve ,
        DeductionID ,
        IsFixed ,
        DueDate 
FROM dbo.Bill WITH(NOLOCK)
WHERE BusinessID={0}
ORDER BY BillMonth,CreateTime

SELECT  BillItemID ,
        BillID ,
        Subject ,
        DueDate ,
        Amount ,
        DueAmt ,
        ReceivedAmt ,
        CreateTime ,
        FullPaidTime ,
        Overdue ,
        SubjectType ,
        OperatorID ,
        IsCurrent ,
        IsShelve ,
        BusinessID ,
        PenaltyIntAmt ,
        LastCalcPenaltyDate 
FROM dbo.BillItem WITH(NOLOCK)
WHERE BillID IN
(SELECT BillID FROM dbo.Bill WHERE BusinessID={0})
