//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace Vcredit.NetSpider.PluginManager.VercodeWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VercodeServiceSoap", Namespace="http://tempuri.org/")]
    public partial class VercodeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecognizeCodeByBytesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecognizeCodeByByUrlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VercodeService() {
            this.Url = global::Vcredit.NetSpider.PluginManager.Properties.Settings.Default.Vcredit_NetSpider_PluginManager_VercodeWebService_VercodeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecognizeCodeByBytesCompletedEventHandler RecognizeCodeByBytesCompleted;
        
        /// <remarks/>
        public event RecognizeCodeByByUrlCompletedEventHandler RecognizeCodeByByUrlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecognizeCodeByBytes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecognizeCodeByBytes([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] picContent, int serviceCompany, int codeType) {
            object[] results = this.Invoke("RecognizeCodeByBytes", new object[] {
                        picContent,
                        serviceCompany,
                        codeType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecognizeCodeByBytesAsync(byte[] picContent, int serviceCompany, int codeType) {
            this.RecognizeCodeByBytesAsync(picContent, serviceCompany, codeType, null);
        }
        
        /// <remarks/>
        public void RecognizeCodeByBytesAsync(byte[] picContent, int serviceCompany, int codeType, object userState) {
            if ((this.RecognizeCodeByBytesOperationCompleted == null)) {
                this.RecognizeCodeByBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecognizeCodeByBytesOperationCompleted);
            }
            this.InvokeAsync("RecognizeCodeByBytes", new object[] {
                        picContent,
                        serviceCompany,
                        codeType}, this.RecognizeCodeByBytesOperationCompleted, userState);
        }
        
        private void OnRecognizeCodeByBytesOperationCompleted(object arg) {
            if ((this.RecognizeCodeByBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecognizeCodeByBytesCompleted(this, new RecognizeCodeByBytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecognizeCodeByByUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecognizeCodeByByUrl(string imageUrl, int serviceCompany, int codeType) {
            object[] results = this.Invoke("RecognizeCodeByByUrl", new object[] {
                        imageUrl,
                        serviceCompany,
                        codeType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecognizeCodeByByUrlAsync(string imageUrl, int serviceCompany, int codeType) {
            this.RecognizeCodeByByUrlAsync(imageUrl, serviceCompany, codeType, null);
        }
        
        /// <remarks/>
        public void RecognizeCodeByByUrlAsync(string imageUrl, int serviceCompany, int codeType, object userState) {
            if ((this.RecognizeCodeByByUrlOperationCompleted == null)) {
                this.RecognizeCodeByByUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecognizeCodeByByUrlOperationCompleted);
            }
            this.InvokeAsync("RecognizeCodeByByUrl", new object[] {
                        imageUrl,
                        serviceCompany,
                        codeType}, this.RecognizeCodeByByUrlOperationCompleted, userState);
        }
        
        private void OnRecognizeCodeByByUrlOperationCompleted(object arg) {
            if ((this.RecognizeCodeByByUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecognizeCodeByByUrlCompleted(this, new RecognizeCodeByByUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RecognizeCodeByBytesCompletedEventHandler(object sender, RecognizeCodeByBytesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecognizeCodeByBytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecognizeCodeByBytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RecognizeCodeByByUrlCompletedEventHandler(object sender, RecognizeCodeByByUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecognizeCodeByByUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecognizeCodeByByUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591